# CodeRabbit configuration file

# General settings
language: "en"

# Review settings
review:
  enabled: true
  auto_approve: false
  drafts: false
  path_filters:
    - "!node_modules/**"
    - "!.next/**"
  path_instructions:
    - patterns: ["*.mdx"]
      instructions: "This is documentation in MDX format. Check for technical accuracy and clarity."
  comment_style: "multiline"

# Release notes generation
release_notes:
  enabled: true
  # Configure sections based on PR labels
  sections:
    - title: "🚀 Features"
      labels: ["feature", "enhancement"]
    - title: "🐛 Bug Fixes"
      labels: ["bug", "fix"]
    - title: "📄 Documentation"
      labels: ["documentation"]
    - title: "🔄 Refactoring"
      labels: ["refactor"]
    - title: "🧪 Testing"
      labels: ["test"]
  # Trigger creation of release notes
  trigger: "on_merge_to_main"
  # Template for release notes
  template: |
    ## Release v{{version}}
    
    {{#each sections}}
    ### {{title}}
    {{#each prs}}
    - {{title}} (#{{number}})
    {{/each}}
    {{/each}}
    
    {{#if uncategorized}}
    ### Other Changes
    {{#each uncategorized}}
    - {{title}} (#{{number}})
    {{/each}}
    {{/if}}
    
    Thank you to all contributors for this release!

# PR summarization
pr_summary:
  enabled: true
  
# Suggested reviewers
suggest_reviewers:
  enabled: true
  max_reviewers: 2